exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awskinesisexporter v0.60.0"
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: "go.opentelemetry.io/collector v0.60.0"

extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.60.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/lumigoauthextension v0.60.0"

receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: "go.opentelemetry.io/collector v0.60.0"

processors:
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.60.0
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.60.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionbykeyprocessor v0.60.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.60.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.60.0"

replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/lumigoauthextension v0.60.0 => github.com/lumigo-io/opentelemetry-collector-contrib/extension/lumigoauthextension 585478a75f3c3c7fe280e98b7aa43b1ad0dcf344
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionbykeyprocessor v0.60.0 => github.com/lumigo-io/opentelemetry-collector-contrib/processor/redactionbykeyprocessor 204e894962b1b48df3797355353eb5d495647f06
#  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcehasherprocessor v0.60.0 => github.com/lumigo-io/opentelemetry-collector-contrib/processor/resourcehasherprocessor 1306ffa7a6f605571f7f265f2e71e8b0957588da
