name: 'Ping code owners'
on:
  issues:
    types: [labeled]

jobs:
  ping-owner:
    if: ${{ contains(github.event.label.name, 'cmd/') || contains(github.event.label.name, 'exporter/') || contains(github.event.label.name, 'extension/') || contains(github.event.label.name, 'pkg/') || contains(github.event.label.name, 'processor/') || contains(github.event.label.name, 'receiver/') }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Run ping-codeowners.sh
        run: ./.github/workflows/scripts/ping-codeowners.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          COMPONENT: ${{ github.event.label.name }}
          SENDER: ${{ github.event.sender.login }}
